MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/Controllers/GamesController.cs
#nullable disable
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

//Generated from Custom Template.
namespace MVC.Controllers
{
    public class GamesController : Controller
    {
        private readonly IGameService _gameService;

        public GamesController(IGameService gameService)
        {
            _gameService = gameService;
        }

        // GET: Games
        public IActionResult Index()
        {
            List<GameModel> gameList = _gameService.GetList();
            return View(gameList);
        }

        // GET: Games/Details/5
        public IActionResult Details(int id)
        {
            GameModel game = _gameService.GetItem(id);
            if (game == null)
            {
                return View("_Error", "Game not found!");
            }
            return PartialView("_Details", game);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewData["PublisherId"] = new SelectList(new List<SelectListItem>(), "Value", "Text");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(GameModel game)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add insert service logic here
                return RedirectToAction(nameof(Index));
            }
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewData["PublisherId"] = new SelectList(new List<SelectListItem>(), "Value", "Text");
            return View(game);
        }

        // GET: Games/Edit/5
        public IActionResult Edit(int id)
        {
            GameModel game = null; // TODO: Add get item service logic here
            if (game == null)
            {
                return NotFound();
            }
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewData["PublisherId"] = new SelectList(new List<SelectListItem>(), "Value", "Text");
            return View(game);
        }

        // POST: Games/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(GameModel game)
        {
            if (ModelState.IsValid)
            {
                // TODO: Add update service logic here
                return RedirectToAction(nameof(Index));
            }
            // TODO: Add get related items service logic here to set ViewData if necessary and update null parameter in SelectList with these items
            ViewData["PublisherId"] = new SelectList(new List<SelectListItem>(), "Value", "Text");
            return View(game);
        }

        // GET: Games/Delete/5
        public IActionResult Delete(int id)
        {
            GameModel game = null; // TODO: Add get item service logic here
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            // TODO: Add delete service logic here
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System.Diagnostics;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/Controllers/PublishersController.cs
#nullable disable
using Business.Models;
using Business.Services;
using Microsoft.AspNetCore.Mvc;

//Generated from Custom Template.
namespace MVC.Controllers
{
    public class PublishersController : Controller
    {
        private readonly IPublisherService _publisherService;

        public PublishersController(IPublisherService publisherService)
        {
            _publisherService = publisherService;
        }

        // GET: Publishers
        public IActionResult Index()
        {
            List<PublisherModel> publisherList = _publisherService.Query().ToList();
            return View(publisherList);
        }

        // GET: Publishers/Details/5
        public IActionResult Details(int id)
        {
            PublisherModel publisher = _publisherService.Query().SingleOrDefault(p => p.Id == id);
            if (publisher == null)
            {
                return View("_Error", "Publisher not found!");
            }
            return View(publisher);
        }

        // GET: Publishers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PublisherModel publisher)
        {
            if (ModelState.IsValid)
            {
                var result = _publisherService.Add(publisher);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public IActionResult Edit(int id)
        {
            PublisherModel publisher = _publisherService.Query().SingleOrDefault(p => p.Id == id);
            if (publisher == null)
            {
                return View("_Error", "Publisher not found!");
            }
            return View(publisher);
        }

        // POST: Publishers/Edit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PublisherModel publisher)
        {
            if (ModelState.IsValid)
            {
                var result = _publisherService.Update(publisher);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Details), new { id = publisher.Id });
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        public IActionResult Delete(int id)
        {
            PublisherModel publisher = _publisherService.Query().SingleOrDefault(p => p.Id == id);
            if (publisher == null)
            {
                return View("_Error", "Publisher not found!");
            }
            return View(publisher);
        }

        // POST: Publishers/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var result = _publisherService.Delete(id);
            TempData["Message"] = result.Message;
            return RedirectToAction(nameof(Index));
        }
	}
}

MVC/Views/Games/Create.cshtml
@model GameModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Create";
}

<h1>@ViewData["Title"]</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="Create">
		@Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row mb-3">
                <label asp-for="Name" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="Description" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Description" class="form-control" />
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="PublishDate" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="PublishDate" class="form-control" />
					<span asp-validation-for="PublishDate" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="Price" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Price" class="form-control" />
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="DownloadCount" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="DownloadCount" class="form-control" />
					<span asp-validation-for="DownloadCount" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="PlayerCountType" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="PlayerCountType" class="form-control" />
					<span asp-validation-for="PlayerCountType" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
				<label asp-for="IsDeleted" class="col-2 col-form-label"></label>
				<div class="col-5" style="padding-top: 7px;">
					<input class="form-check-input" asp-for="IsDeleted" />
                </div>
            </div>
            <div class="row mb-3">
                <label asp-for="PublisherId" class="col-2 col-form-label"></label>
				<div class="col-5">
					<select asp-for="PublisherId" class="form-select" asp-items="ViewBag.PublisherId">
						<option value="">-- Select --</option>
					</select>
					<span asp-validation-for="PublisherId" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="Guid" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Guid" class="form-control" />
					<span asp-validation-for="Guid" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
				<div class="offset-2 col-5">
					<input type="submit" value="Save" class="btn btn-primary" />
					&nbsp;&nbsp;
                    <button type="reset" class="btn btn-outline-primary">Reset</button>
					&nbsp;&nbsp;
					<a asp-action="Index">Back to List</a>
				</div>
            </div>
        </form>
    </div>
</div>

MVC/Views/Games/Delete.cshtml
@model GameModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Delete";
}

<h1>@ViewData["Title"]</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="row">
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.PublishDate)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.DownloadCount)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.DownloadCount)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.PlayerCountType)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.PlayerCountType)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.PublisherId)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.PublisherId)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.Guid)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.Guid)
        </dd>
    </dl>
    
    <form asp-action="Delete">
	@Html.AntiForgeryToken()
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Yes" class="btn btn-danger" />&nbsp;&nbsp;
        <a asp-action="Index" class="btn btn-success">No</a>
    </form>
</div>

MVC/Views/Games/Edit.cshtml
@model GameModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Edit";
}

<h1>@ViewData["Title"]</h1>

<h4>Game</h4>
<hr />
<div class="row">
    <div class="col-12">
        <form asp-action="Edit">
		@Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="row mb-3">
                <label asp-for="Name" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Name" class="form-control" />
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="Description" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Description" class="form-control" />
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="PublishDate" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="PublishDate" class="form-control" />
					<span asp-validation-for="PublishDate" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="Price" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Price" class="form-control" />
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="DownloadCount" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="DownloadCount" class="form-control" />
					<span asp-validation-for="DownloadCount" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
                <label asp-for="PlayerCountType" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="PlayerCountType" class="form-control" />
					<span asp-validation-for="PlayerCountType" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
				<label asp-for="IsDeleted" class="col-2 col-form-label"></label>
				<div class="col-5" style="padding-top: 7px;">
					<input class="form-check-input" asp-for="IsDeleted" />
                </div>
            </div>
            <div class="row mb-3">
                <label asp-for="PublisherId" class="col-2 col-form-label"></label>
				<div class="col-5">
					<select asp-for="PublisherId" class="form-select" asp-items="ViewBag.PublisherId">
						<option value="">-- Select --</option>
					</select>
					<span asp-validation-for="PublisherId" class="text-danger"></span>
				</div>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="row mb-3">
                <label asp-for="Guid" class="col-2 col-form-label"></label>
				<div class="col-5">
					<input asp-for="Guid" class="form-control" />
					<span asp-validation-for="Guid" class="text-danger"></span>
				</div>
            </div>
            <div class="row mb-3">
				<div class="offset-2 col-5">
					<input type="submit" value="Save" class="btn btn-primary" />
					&nbsp;&nbsp;
                    <button type="reset" class="btn btn-outline-primary">Reset</button>
					&nbsp;&nbsp;
					<a asp-action="Index">Back to List</a>
				</div>
            </div>
        </form>
    </div>
</div>

MVC/Views/Games/Index.cshtml
@model IEnumerable<GameModel>
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Games";
}

<h1>@ViewData["Title"]</h1>

@if (TempData["Message"] is not null)
{
    <p class="bg-warning text-black">@TempData["Message"]</p>
}

<p>
    <a asp-action="Create">Create New</a>
</p>

<p class="bg-info text-dark">@Model.Count() game(s) found.</p>

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublishDateOutput)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PriceOutput)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PlayerCountTypeOutput)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublisherOutput.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublishDateOutput)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PriceOutput)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PlayerCountTypeOutput)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublisherOutput.Name)
                    </td>
                    <td class="text-end">
                        <!-- Bootstrap 5 Modal: --> 
                        <a href="#" class="showmodallink text-primary" data-target="/Games/Details/@item.Id">Details</a>
                        &nbsp;|&nbsp;
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        &nbsp;|&nbsp;
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<!-- Bootstrap 5 Modal: -->
<div class="modal">
    <div class="modal-lg modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Game</h5>
                <button type="button" class="btn-close closemodalbutton" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Dinamik olarak sunucudan dönen partial view'lar üzerinden doldurulacak -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary closemodalbutton">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <!-- Bootstrap 5 Modal: -->
    <script>
        //$(document).ready(function () {
        $(function () {
            $(".closemodalbutton").click(function () {
                $(".modal").hide();
            });

            $(".showmodallink").click(function (event) {
                event.preventDefault();

                var route = $(this).data("target");

                $.get(route, function () {

                })
                .done(function (partialView) {
                    $(".modal .modal-body").html(partialView);
                })
                .fail(function (response) {
                    $(".modal .modal-body").html('<span class="text-danger">' + response.responseText + '</span>');
                });

                $(".modal").show();
            })
        });
    </script>
}

MVC/Views/Games/_Details.cshtml
@using DataAccess.Enums

@model GameModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-9">
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>
<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd class="col-9">
        @Html.DisplayFor(model => model.Description)
    </dd>
</dl>
<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.PublishDateOutput)
    </dt>
    <dd class="col-9">
        @Html.DisplayFor(model => model.PublishDateOutput)
    </dd>
</dl>
<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.PriceOutput)
    </dt>
    <dd class="col-9">
        @Html.DisplayFor(model => model.PriceOutput)
    </dd>
</dl>
<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.DownloadCount)
    </dt>
    <dd class="col-9">
        @Html.DisplayFor(model => model.DownloadCount)
    </dd>
</dl>
<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.PlayerCountTypeOutput)
    </dt>
    <dd class="col-9">
        @Html.DisplayFor(model => model.PlayerCountTypeOutput)
    </dd>
</dl>
<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.PublisherOutput.Name)
    </dt>
    <dd class="col-9">
        @Html.DisplayFor(model => model.PublisherOutput.Name)
    </dd>
</dl>
<dl class="row">
    <dt class="col-3">
        @Html.DisplayNameFor(model => model.UsersOutput)
    </dt>
    <dd class="col-9">
        @{
            if (Model.UsersOutput is not null)
            {
                foreach (var user in Model.UsersOutput)
                {
                    if ((Sex)user.Sex == Sex.Woman)
                    {
                        <span class="badge" style="background-color:#FF69B4;color:#fff;">@user.UserName</span>
                    }
                    else
                    {
                        <span class="badge badge-primary text-white">@user.UserName</span>
                    }
                    <br />
                }
            }
        }
    </dd>
</dl>

MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC/Views/Publishers/Create.cshtml
@model PublisherModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Create Publisher";
}

<div class="container">

    <h1>@ViewData["Title"]</h1>

    <h4>Publisher</h4>
    <hr />
    <div class="row">
        <div class="col-12">
            <form asp-action="Create">
		    @Html.AntiForgeryToken()
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="row mb-3">
                    <label asp-for="Name" class="col-2 col-form-label"></label>
				    <div class="col-5">
					    <input asp-for="Name" class="form-control" />
					    <span asp-validation-for="Name" class="text-danger"></span>
				    </div>
                </div>
                <div class="row mb-3">
				    <div class="offset-2 col-5">
					    <input type="submit" value="Save" class="btn btn-primary" />
					    &nbsp;&nbsp;
                        <button type="reset" class="btn btn-outline-primary">Reset</button>
					    &nbsp;&nbsp;
					    <a asp-action="Index">Back to List</a>
				    </div>
                </div>
            </form>
        </div>
    </div>

</div>

@section Scripts {
    @* Client Side Validation *@
    <partial name="_ValidationScriptsPartial" />
}

MVC/Views/Publishers/Delete.cshtml
@model PublisherModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Delete Publisher";
}

<div class="container">

    <h1>@ViewData["Title"]</h1>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <partial name="_Details" model="Model" />
    
        <form asp-action="Delete">
	    @Html.AntiForgeryToken()
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Yes" class="btn btn-danger" />&nbsp;&nbsp;
            <a asp-action="Index" class="btn btn-success">No</a>
        </form>
    </div>

</div>

MVC/Views/Publishers/Details.cshtml
@model PublisherModel
@*Generated from Custom Template.*@
@*Model namespace using directive should be added to _ViewImports.cshtml.*@

@{
    ViewData["Title"] = "Publisher Details";
}

<div class="container">

    <h1>@ViewData["Title"]</h1>

    @if (TempData["Message"] is not null)
    {
        <p class="bg-warning text-black">@TempData["Message"]</p>
    }

    <partial name="_Details" model="Model" />
    
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>&nbsp;|&nbsp;
        <a asp-action="Index">Back to List</a>
    </div>

</div>

MVC/Views/Shared/_Error.cshtml
@model string

@{
    ViewData["Title"] = "Error!";
}

<h1 class="text-danger">@ViewData["Title"]</h1>

@if (string.IsNullOrWhiteSpace(Model))
{
    <h2 class="text-danger">An error occurred while processing your request.</h2>
}
else
{
    <h2 class="text-danger">@Model</h2>
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* Menü *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publishers" asp-action="Index">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Games</a>
                        </li>

                        @* User Management *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2023 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>